language: ruby
rvm:
  - 2.1.0

#script:
#  - bundle exec rake test

env:
  global:
    - RAILS_ENV=test

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake --trace test
before_script:
  - mysql -e 'create database qsi_grupo_facultad'
  - psql -c 'create database qsi_grupo_facultad;' -U postgres
