language: ruby
rvm:
  - 2.1.0

#script:
#  - bundle exec rake test

env:
  global:
    - RAILS_ENV=test

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
  - bundle exec rake test --trace
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
